FROM alpine:3.6
RUN apk add --no-cache ca-certificates \
                       bash \
                       curl \
                       rsync \
                       openssh \
                       git