# NAME:     shebgregor/alpine-rsync-git
FROM alpine:3.6

LABEL maintainer "Michael Popsuev <sheb.gregor@gmail.com>"

RUN apk add --no-cache ca-certificates \
                       bash \
                       curl \
                       rsync \
                       openssh \
                       git