# NAME:   shebgregor/ubuntu-autotools
FROM ubuntu:16.04

LABEL maintainer "Michael Popsuev <sheb.gregor@gmail.com>"

RUN true \
 && apt-get update \
 && apt-get install -y \
	git \
	build-essential \
	pkg-config \
	autoconf \
	automake \
	libtool \
	bison \
	flex \
	libpq-dev \
	libboost-all-dev\
	gcc \
	g++ \
	cpp
