FROM ubuntu:16.04

MAINTAINER sheb.gregor@gmail.com<Michael Popsuev>

RUN true \
 && apt-get update \
 && apt-get install -y \
	git \
	build-essential \
	pkg-config \
	autoconf \
	automake \
	libtool \
	bison \
	flex \
	libpq-dev \
	libboost-all-dev\
	gcc \
	g++ \
	cpp
