# NAME:   shebgregor/debian-postgres-clang
FROM postgres:9.5

LABEL maintainer "Michael Popsuev <sheb.gregor@gmail.com>"

RUN apt-get update
RUN apt-get install -y git build-essential pkg-config autoconf automake libtool bison flex libpq-dev clang++-3.5 gcc-4.9 g++-4.9 cpp-4.9 libboost-all-dev libboost-all-dev